[build]
builder = "nixpacks"

[deploy]
numReplicas = 1
restartPolicyType = "ON_FAILURE"

# Frontend Service Configuration
[[services]]
name = "frontend"
rootDirectory = "biblemap/frontend"
buildCommand = "npm ci && npm run build"
startCommand = "npm start"
healthcheckPath = "/"
port = 3000

[[services.domains]]
domain = "biblemap.up.railway.app"

# Backend Service Configuration
[[services]]
name = "backend"
rootDirectory = "biblemap/backend"
buildCommand = "npm ci && npx prisma generate && npm run build"
startCommand = "npx prisma migrate deploy && npm start"
healthcheckPath = "/health"
port = 4000

# PostgreSQL is added via Railway UI